### ISSUE TITLE
Meeting #1 Agenda - Sept 30, 2021

### ISSUE THREAD

**Issue by jedelman8** [nautobot/community#1]
Please leave comments on what items should be included for discussion for this meeting:

## Agenda

* Announcements & Reminders
* Overview of Issue Intake Process & Community Contributions
* Stale Pull Requests Review
* Q&A about Upcoming Features
* New Ideas/Proposals that need traction/attention (that already have an Issue or Discussion Open)
* Open Discussion & Forum

Please include a link to any issue or PR that you wish to discuss.

**Comment by jedelman8** [comment]
As the first meeting, it may be good to cover the work intake process.

**Comment by jathanism** [comment]
From Eric Jacob on Slack for Q&A about upcoming features:

- The future of the UI (have you considered client-side javascript frameworks like Vue or React?)
- DCIM missing features like floor plan
- Ansible and Terraform runners for jobs
- Secrets (https://github.com/nautobot/nautobot/pull/868)
- Firewall objects (https://github.com/nautobot/nautobot/discussions/904)
- Scheduling & Approvals for jobs (https://github.com/nautobot/nautobot/pull/805)
