### ISSUE TITLE
Meeting Agenda #3 - November 23, 2021

### ISSUE THREAD

**Issue by jathanism** [nautobot/community#11]
**Please note that due to the Thanksgiving holiday on November 25, we are moving this month's meeting to Tuesday, November 23!**

Please leave comments on what items should be included for discussion for this meeting:

## Agenda

* Announcements & Reminders
* Stale Pull Requests Review
* Q&A about Upcoming Features
* New Ideas/Proposals that need traction/attention (that already have an Issue or Discussion Open)
* Q&A and FYI about Developer Experience
* Open Discussion & Forum

Please include a link to any issue or PR that you wish to discuss.

**Comment by jathanism** [comment]
- Discuss and garner feedback for reorganizing top-level menu items (e.g. moving Power into the Devices menu as one suggestion) for v1.3.0 release.

**Comment by glennmatthews** [comment]
Some suggestions:

- Announcements & Reminders
  - Nautobot 1.2.0b1 is out, feedback will be valuable!
- Stale Pull Requests Review
  - https://github.com/nautobot/nautobot/pull/811 (changes requested on 1 October)
  - https://github.com/nautobot/nautobot/pull/925 (not an easy problem to solve; proposed solution needs to be reviewed in depth by core team)
  - https://github.com/nautobot/nautobot/pull/1029 (draft, pending review by core team)
  - https://github.com/nautobot/nautobot/pull/1046 (updated by submitter, needs re-review by core team)
  - https://github.com/nautobot/nautobot/pull/1080 (pending review by core team)
- Q&A about Upcoming Features
  - GraphQL multi-level filtering (https://github.com/nautobot/nautobot/pull/799)
  - Secrets, groups, and providers (https://github.com/nautobot/nautobot/pull/868)
  - Admin configuration (https://github.com/nautobot/nautobot/pull/1079)
  - Job scheduling/approval
  - Organizational branding (https://github.com/nautobot/nautobot/pull/924)
- New Ideas/Proposals that need traction/attention (that already have an Issue or Discussion Open)
  - Contact modeling (https://github.com/nautobot/nautobot/discussions/1071)
  - Multiple untagged VLANs on an interface (https://github.com/nautobot/nautobot/discussions/1045)
  - More generalized Reservation model (https://github.com/nautobot/nautobot/discussions/1033)
  - Segment Routing modeling (https://github.com/nautobot/nautobot/discussions/1014)
  - REST API endpoint for token management (https://github.com/nautobot/nautobot/discussions/471)
  - Reorganization of menus (move Power under Devices, move Jobs to its own menu, etc.)
- Q&A and FYI about Developer Experience
  - New plugins list view and detail view, link pattern for plugin "home" and "config" views (https://github.com/nautobot/nautobot/pull/935)
  - `nautobot_database_ready` signal (https://github.com/nautobot/nautobot/pull/820)
  - Plugin defined banners (https://github.com/nautobot/nautobot/pull/756)
  - New object detail view base template (https://github.com/nautobot/nautobot/pull/737)
  - Software defined home page, extensible by plugins (https://github.com/nautobot/nautobot/pull/716)
- Open Discussion & Forum
