### ISSUE TITLE
Meeting Agenda #4 - December 21, 2021

### ISSUE THREAD

**Issue by jathanism** [nautobot/community#15]
**Please note that due to the Christmas holiday on December 25, we are moving this month's meeting to Tuesday, December 21!**

Please leave comments on what items should be included for discussion for this meeting:

## Agenda

* Announcements & Reminders
* Stale Pull Requests Review
* Q&A about Upcoming Features
* New Ideas/Proposals that need traction/attention (that already have an Issue or Discussion Open)
* Q&A and FYI about Developer Experience
* Open Discussion & Forum

Please include a link to any issue or PR that you wish to discuss.

**Comment by glennmatthews** [comment]
Announcements: Nautobot 1.2.0/1.2.1 released, have begun development toward 1.3.0.

Stale PRs: none needing a callout at this time. We'll re-review open PRs (especially draft ones) now that 1.2.0 is out the door.

Upcoming features (https://github.com/nautobot/nautobot/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v1.3.0+%22, though we probably need to prune this list somewhat)
- Unified Device/VM data model (https://github.com/nautobot/nautobot/issues/1178)
- Lots of refinements to Jobs UI/UX (various issues)
- Enhanced IPAM model relationships (https://github.com/nautobot/nautobot/issues/1032)
- Dynamic object groups (https://github.com/nautobot/nautobot/issues/896)
- Notes (https://github.com/nautobot/nautobot/issues/767)

**Comment by jathanism** [comment]
New Ideas/Proposals

- "I wish" feedback link (https://github.com/nautobot/nautobot/issues/1175)

**Comment by glennmatthews** [comment]
Minutes: #17.
