### ISSUE TITLE
Meeting Agenda #6 - February 24, 2022

### ISSUE THREAD

**Issue by bryanculver** [nautobot/community#22]
Please leave comments on what items should be included for discussion for this meeting:

Agenda
---

- Announcements & Reminders
- Stale Pull Requests Review
- Q&A about Upcoming Features
- New Ideas/Proposals that need traction/attention (that already have an Issue or Discussion Open)
- Q&A and FYI about Developer Experience
- Open Discussion & Forum

Please include a link to any issue or PR that you wish to discuss.

**Comment by jifox** [comment]
Is the requirement for python 3.7 blocking the merge?
https://github.com/nautobot/nautobot-plugin-secrets-providers/pull/22

btw. thanks for making nautobot such a great tool

Josef

**Comment by bryanculver** [comment]
Agenda Items:
- Announcing Patch Release Schedule
- Dropping 3.6 Support

**Comment by jathanism** [comment]
> Is the requirement for python 3.7 blocking the merge? [nautobot/nautobot-plugin-secrets-providers#22](https://github.com/nautobot/nautobot-plugin-secrets-providers/pull/22)
> 
> btw. thanks for making nautobot such a great tool
> 
> Josef

We'll cover this today!
